### ISSUE TITLE
Something Error

### ISSUE THREAD

**Issue by zichenace** [BlueMap-Minecraft/BlueMap#357]
Where？Occurs when I visit  the WEB Map.
What？  Error content：
```
[20:27:02 ERROR]: [BlueMap] Failed to save settings for map 'world'!
java.nio.file.FileAlreadyExistsException: bluemap\web\maps\world\settings.json.filepart -> bluemap\web\maps\world\settings.json
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
        at java.nio.file.Files.move(Files.java:1430) ~[?:?]
        at de.bluecolored.bluemap.core.util.FileHelper.move(FileHelper.java:63) ~[BlueMap-3.5-spigot.jar:?]
        at de.bluecolored.bluemap.core.util.FileHelper.lambda$createFilepartOutputStream$0(FileHelper.java:50) ~[BlueMap-3.5-spigot.jar:?]
        at de.bluecolored.bluemap.core.util.WrappedOutputStream.close(WrappedOutputStream.java:71) ~[BlueMap-3.5-spigot.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:443) ~[?:?]
        at sun.nio.cs.StreamEncoder.lockedClose(StreamEncoder.java:241) ~[?:?]
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:226) ~[?:?]
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:267) ~[?:?]
        at de.bluecolored.bluemap.core.map.BmMap.saveMapSettings(BmMap.java:193) ~[BlueMap-3.5-spigot.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.save(BmMap.java:133) ~[BlueMap-3.5-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.save(Plugin.java:418) ~[BlueMap-3.5-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin$1.run(Plugin.java:244) ~[BlueMap-3.5-spigot.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]
```

When？  If I visit the webpage, this error may appear on the console

**Comment by TBlueF** [comment]
Please provide more info..
-> https://github.com/BlueMap-Minecraft/BlueMap/blob/034d8b097afb2aeddab28f593cc62b55c73e5b56/.github/CONTRIBUTING.md#guidlines-for-a-good-bug-issue
& How often does this error occur?

**Comment by zichenace** [comment]
More information has been provided.

**Comment by kraoc** [comment]
Got the same:

```
[19:09:24] [BlueMap-Plugin-Daemon-Timer/ERROR]: Failed to save settings for map 'nether'!
java.nio.file.FileAlreadyExistsException: bluemap/web/maps/nether/settings.json
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:449) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266) ~[?:?]
        at java.nio.file.Files.move(Files.java:1432) ~[?:?]
        at de.bluecolored.bluemap.core.util.FileHelper.move(FileHelper.java:63) ~[bluemap.jar:?]
        at de.bluecolored.bluemap.core.util.FileHelper.lambda$createFilepartOutputStream$0(FileHelper.java:50) ~[bluemap.jar:?]
        at de.bluecolored.bluemap.core.util.WrappedOutputStream.close(WrappedOutputStream.java:71) ~[bluemap.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347) ~[?:?]
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
        at de.bluecolored.bluemap.core.map.BmMap.saveMapSettings(BmMap.java:193) [bluemap.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.save(BmMap.java:133) [bluemap.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.save(Plugin.java:418) [bluemap.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin$1.run(Plugin.java:244) [bluemap.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) [?:?]
        at java.util.TimerThread.run(Timer.java:516) [?:?]
[19:09:24] [BlueMap-Plugin-Daemon-Timer/ERROR]: Failed to save settings for map 'end'!
java.nio.file.FileAlreadyExistsException: bluemap/web/maps/end/settings.json
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:449) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266) ~[?:?]
        at java.nio.file.Files.move(Files.java:1432) ~[?:?]
        at de.bluecolored.bluemap.core.util.FileHelper.move(FileHelper.java:63) ~[bluemap.jar:?]
        at de.bluecolored.bluemap.core.util.FileHelper.lambda$createFilepartOutputStream$0(FileHelper.java:50) ~[bluemap.jar:?]
        at de.bluecolored.bluemap.core.util.WrappedOutputStream.close(WrappedOutputStream.java:71) ~[bluemap.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347) ~[?:?]
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
        at de.bluecolored.bluemap.core.map.BmMap.saveMapSettings(BmMap.java:193) [bluemap.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.save(BmMap.java:133) [bluemap.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.save(Plugin.java:418) [bluemap.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin$1.run(Plugin.java:244) [bluemap.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) [?:?]
        at java.util.TimerThread.run(Timer.java:516) [?:?]
[19:09:24] [BlueMap-Plugin-Daemon-Timer/ERROR]: Failed to save settings for map 'overworld'!
java.nio.file.FileAlreadyExistsException: bluemap/web/maps/overworld/settings.json
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:449) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266) ~[?:?]
        at java.nio.file.Files.move(Files.java:1432) ~[?:?]
        at de.bluecolored.bluemap.core.util.FileHelper.move(FileHelper.java:63) ~[bluemap.jar:?]
        at de.bluecolored.bluemap.core.util.FileHelper.lambda$createFilepartOutputStream$0(FileHelper.java:50) ~[bluemap.jar:?]
        at de.bluecolored.bluemap.core.util.WrappedOutputStream.close(WrappedOutputStream.java:71) ~[bluemap.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347) ~[?:?]
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
        at de.bluecolored.bluemap.core.map.BmMap.saveMapSettings(BmMap.java:193) [bluemap.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.save(BmMap.java:133) [bluemap.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.save(Plugin.java:418) [bluemap.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin$1.run(Plugin.java:244) [bluemap.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) [?:?]
        at java.util.TimerThread.run(Timer.java:516) [?:?]
```
I get this 'sometimes' when I show the web app to display map.

But not avery time.

How can I debug ?

MC 1.19.2 + Fabric under Pterodactyl

```
[19:10:44] [main/INFO]: Loading 107 mods:
	- balm-fabric 4.5.2+0
	- bluemap 3.5
	- bluemapadvancedmarker 2022.10.1
	- chunky 1.3.38
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- collective-fabric 5.14
	- com_electronwill_night-config_core 3.6.6 via servercore
	- com_electronwill_night-config_toml 3.6.6 via servercore
	- com_fasterxml_jackson_core_jackson-annotations 2.13.3 via commandaliases
	- com_fasterxml_jackson_core_jackson-core 2.13.3 via commandaliases
	- com_fasterxml_jackson_core_jackson-databind 2.13.3 via commandaliases
	- com_fasterxml_jackson_dataformat_jackson-dataformat-toml 2.13.3 via commandaliases
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.13.3 via commandaliases
	- com_github_llamalad7_mixinextras 0.1.0 via servercore
	- com_moandjiezana_toml_toml4j 0.7.2 via fabricproxy-lite
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- commandaliases 0.9.3+mc1.19-build.49
	- common-protection-api 1.0.0 via universal-graves
	- doubledoors-fabric 3.8
	- ec-core 1.3.0-mc1.19.2 via essential_commands
	- essential_commands 0.29.0-mc1.19.2-3
	- explorerscompass 1.19.2-2.2.0-fabric
	- fabric-api 0.64.0+1.19.2
	- fabric-api-base 0.4.12+93d8cb8290 via fabric-api
	- fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
	- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.35+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.4.0+6064db2a90 via fabric-api
	- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
	- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.2.2+b598f4ac90 via fabric-api
	- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
	- fabric-entity-events-v1 1.4.19+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
	- fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
	- fabric-item-groups-v0 0.3.32+70efcffe90 via fabric-api
	- fabric-language-kotlin 1.8.5+kotlin.1.7.20
	- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
	- fabric-loot-api-v2 1.1.6+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.9+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.17+33fbc73890 via fabric-api
	- fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
	- fabric-networking-v0 0.3.22+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.14+93d8cb8290 via fabric-api
	- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
	- fabric-permissions-api-v0 0.2-SNAPSHOT via bluemapadvancedmarker
	- fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.15+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.0+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.7.2+70efcffe90 via fabric-api
	- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
	- fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
	- fabricloader 0.14.10
	- fabricproxy-lite 2.3.0
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via collective-fabric
	- hologram-api 0.2.2+1.19 via universal-graves
	- java 17
	- journeymap 5.9.0beta2
	- journeymap-api-fabric 1.19.1-1.9-fabric-SNAPSHOT via journeymap
	- krypton 0.2.1
	- lazydfu 0.1.3
	- lithium 0.10.1
	- me_lucko_spark-api 0.1-SNAPSHOT via servercore
	- minecraft 1.19.2
	- naturescompass 1.19.2-2.0.4-fabric
	- org_iq80_leveldb_leveldb 0.12 via commandaliases
	- org_iq80_leveldb_leveldb-api 0.12 via commandaliases
	- org_jetbrains_kotlin_kotlin-reflect 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- packet_tweaker 0.3.0+1.18.2 via polymer
	- placeholder-api 2.0.0-pre.1+1.19.2 via servercore
	- plan 5.5 build 1984
	- player_events 2.4.1
	- player_events_api 2.4.1 via player_events
	- playerabilitylib 1.6.0 via essential_commands
	- polymer 0.2.17+1.19.2 via universal-graves
	- polymer-registry-sync-manipulator 0.0.3+1.19.2 via polymer
	- replantingcrops-fabric 4.2
	- server_translations_api 1.4.18+1.19.2 via universal-graves
	- servercore 1.3.3-1.19.2
	- sgui 1.1.5+1.19.1 via universal-graves
	- smoothboot 1.19-1.7.1
	- spark 1.9.40
	- starlight 1.1.1+fabric.ae22326
	- treeharvester-fabric 5.8
	- universal-graves 2.1.3+1.19.2
	- waystones 11.1.0
	- worldedit 7.2.12+6240-87f4ae1
```

**Comment by zichenace** [comment]
Hello？Can we fix this problem？

**Comment by TBlueF** [comment]
@zichenace Sorry, i forgot to respond here..
The code-line causing this particular error has been fixed in Version 3.6. But it shouldn't have occurred in the first place, so ..
can you try release 3.6 and check if this fixes your issue, or how the error has changed?

**Comment by zichenace** [comment]
Thank you reply me. I have now finished updating. This error still exists. But this does not affect the normal use.
Is it possible that I use Windows Server 2019 or jdk19 ?

This log just happened：↓
```
[23:40:07 ERROR]: [BlueMap] Failed to save settings for map 'world'!
java.nio.file.FileAlreadyExistsException: bluemap\web\maps\world\settings.json.filepart -> bluemap\web\maps\world\settings.json
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
        at java.nio.file.Files.move(Files.java:1430) ~[?:?]
        at de.bluecolored.bluemap.core.util.FileHelper.move(FileHelper.java:63) ~[BlueMap-3.6-spigot.jar:?]
        at de.bluecolored.bluemap.core.util.FileHelper.lambda$createFilepartOutputStream$0(FileHelper.java:50) ~[BlueMap-3.6-spigot.jar:?]
        at de.bluecolored.bluemap.core.util.WrappedOutputStream.close(WrappedOutputStream.java:71) ~[BlueMap-3.6-spigot.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:443) ~[?:?]
        at sun.nio.cs.StreamEncoder.lockedClose(StreamEncoder.java:241) ~[?:?]
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:226) ~[?:?]
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:267) ~[?:?]
        at de.bluecolored.bluemap.core.map.BmMap.saveMapSettings(BmMap.java:193) ~[BlueMap-3.6-spigot.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.save(BmMap.java:133) ~[BlueMap-3.6-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.save(Plugin.java:418) ~[BlueMap-3.6-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin$1.run(Plugin.java:244) ~[BlueMap-3.6-spigot.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]
[23:42:07 ERROR]: [BlueMap] Failed to save settings for map 'world'!
java.nio.file.AccessDeniedException: bluemap\web\maps\world\settings.json
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275) ~[?:?]
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110) ~[?:?]
        at java.nio.file.Files.deleteIfExists(Files.java:1191) ~[?:?]
        at de.bluecolored.bluemap.core.util.FileHelper.lambda$createFilepartOutputStream$0(FileHelper.java:47) ~[BlueMap-3.6-spigot.jar:?]
        at de.bluecolored.bluemap.core.util.WrappedOutputStream.close(WrappedOutputStream.java:71) ~[BlueMap-3.6-spigot.jar:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:188) ~[?:?]
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:443) ~[?:?]
        at sun.nio.cs.StreamEncoder.lockedClose(StreamEncoder.java:241) ~[?:?]
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:226) ~[?:?]
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:267) ~[?:?]
        at de.bluecolored.bluemap.core.map.BmMap.saveMapSettings(BmMap.java:193) ~[BlueMap-3.6-spigot.jar:?]
        at de.bluecolored.bluemap.core.map.BmMap.save(BmMap.java:133) ~[BlueMap-3.6-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.save(Plugin.java:418) ~[BlueMap-3.6-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin$1.run(Plugin.java:244) ~[BlueMap-3.6-spigot.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]
>
```

**Comment by TBlueF** [comment]
If the same error still persists then this is very likely an issue with your OS or the JRE/JVM that you are using ..

Make sure your files are not accessed and locked by any other app/process while bluemap is running.
And based on the `AccessDeniedException` ..  **make sure that bluemap has enough permissions to write/replace/delete those files**.

If you say that this only happens when you open the webapp... are you using an external webserver instead of the internal one? Then make sure that this webserver is not trying to write to those files/locking them.
Or maybe you somehow changed the permissions for existing files and now bluemap has not enough permissions to overwrite them.

Since i am very confident that this issue is not a bug but a setup-problem on your end and i can not reproduce it, i'll close this here on github.
If you need support, you can always visit us on our [discord](https://discord.gg/zmkyJa3) :)

**Comment by kraoc** [comment]
On a personnal way.. I used Bluemap/BAM on a SMB share inside a Docker in Docker (Pterodactyl inside Docker)
I resolved my issue using SQL storage in Bluemap ^^
Permissions are a mess sometimes.
